services:
  database:
    image: 'postgres:15.15'
    container_name: "postgresql"
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: passgre
      POSTGRES_DB: english
    networks:
      - postgres-network
    volumes:
      - ./.postgre_data:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4:9.10'
    container_name: "pgadmin"
    ports:
      - 15433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pogre@bk.ru
      PGADMIN_DEFAULT_PASSWORD: pagre
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - .pgadmin-data:/var/lib/pgadmin
  
networks: 
  postgres-network:
    driver: bridge